phrase:
  project_id: ab316b36eadbb8213488c530566c94ed

  push:
    sources:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true
          tags: custom_tag

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json


