phrase:
  project_id: 827b39bc76a90522ecb2b28d1312f7b1

  push:
    sources:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json


