phrase:
  project_id: a8004b7565629bbd3d6aa3508b1b2b33

  push:
    sources:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json


