phrase:
  project_id: 

  push:
    sources:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true
          autotranslate: true

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
